[package]
name = "nes_emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.15.0"
bitflags = "2.3.3"
cpal = "0.15.3"
sdl2 = { version = "0.37.0", features = ["unsafe_textures"] }
